version: "3.9"

services:
  mssql:
    container_name: manuel-antonio-explorer-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    user: "10001:0" 
    environment:
      ACCEPT_EULA:"Y"
      MSSQL_SA_PASSWORD:"${SQL_SA_PASSWORD}"
      MSSQL_BACKUP_DIR=:"/var/opt/mssql/backups"
    ports:
      - 1433:1433
    volumes:
      - ./data/mssql/backups:/var/opt/mssql/backups
      - ./data/mssql/data:/var/opt/mssql/data
      - ./data/mssql/log:/var/opt/mssql/log

networks:
  default:
    name: manuel-antonio-explorer-mssql-net