import "./globals.css";
import { Suspense } from "react";
import Providers from "./providers";
import type { Metadata } from "next";
import EmotionRegistry from "@src/EmotionRegistry";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manuel Antonio Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EmotionRegistry>
          <Providers>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </Providers>
        </EmotionRegistry>
      </body>
    </html>
  );
}
