name: CI/CD - WebStackBase

on:
  push:
    branches:
      - principal
  pull_request:
    branches:
      - principal

jobs:
  build-and-test:
    name: 🔨 Build & ✅ Test
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "${{ secrets.SQL_SA_PASSWORD }}"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: 🧩 Install dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 9.0.4
  
      - name: 🛠️ Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: 📦 Restore dependencies
        run: dotnet restore ./api/WebStackBase.Api.sln

      - name: 🛠️ Build
        run: dotnet build ./api/WebStackBase.Api.sln --configuration Release --no-restore

      - name: 🔄 Run EF Core migrations
        run: dotnet ef database update --project ./api/WebStackBase.Infrastructure --startup-project ./api/WebStackBase.WebAPI
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

      - name: 🧪 Run tests
        run: dotnet test ./api/WebStackBase.Tests/WebStackBase.Tests.csproj --verbosity normal

      - name: 📤 Publish WebAPI
        run: dotnet publish ./api/WebStackBase.WebAPI/WebStackBase.WebAPI.csproj --configuration Release --output ./api/WebStackBase.WebAPI/publish

      - name: 📁 Create resource manager directory on the VPS if not exists
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            if [ ! -d '/var/www/resource-manager' ]; then
              mkdir -p /var/www/resource-manager;
              echo 'Directory /var/www/resource-manager created.';
            else
              echo 'Directory /var/www/resource-manager already exists.';
            fi
      
            # Create the email-templates directory if it doesn't exist
            if [ ! -d '/var/www/resource-manager/email-templates' ]; then
              mkdir -p /var/www/resource-manager/email-templates;
              echo 'Directory /var/www/resource-manager/email-templates created.';
            else
              echo 'Directory /var/www/resource-manager/email-templates already exists.';
            fi
      
            # Create the gallery directory if it doesn't exist
            if [ ! -d '/var/www/resource-manager/gallery' ]; then
              mkdir -p /var/www/resource-manager/gallery;
              echo 'Directory /var/www/resource-manager/gallery created.';
            else
              echo 'Directory /var/www/resource-manager/gallery already exists.';
            fi
      
            # Change ownership of the directories to www-data
            chown -R www-data:www-data /var/www/resource-manager
            # Set read, write, and execute permissions for www-data
            chmod -R 755 /var/www/resource-manager
          "

      - name: 📁 Copy email templates to VPS
        run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
            chmod 600 private_key
        
            # Define template folder on VPS
            TEMPLATE_DIR="/var/www/resource-manager/email-templates"
            BACKUP_DIR="/var/www/resource-manager/email-templates-backup-$(date +%Y%m%d%H%M%S)"
            TEMP_DIR="/var/www/resource-manager/email-templates-temp"
        
            # Backup current templates
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              mv $TEMPLATE_DIR $BACKUP_DIR || exit 1
            "
        
            # Clean temp folder
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              rm -rf $TEMP_DIR
            "
        
            # Copy new templates to temp folder
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key -r ./api/WebStackBase.WebAPI/publish/EmailTemplates/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$TEMP_DIR
        
            # Move new templates to the final location
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              mv $TEMP_DIR $TEMPLATE_DIR
            "

            # Remove backup folder
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              rm -rf $BACKUP_DIR
            "
        
            # Clean up
            rm private_key

      - name: 🚀 Setup and deploy API to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

          # Create the destination directory on VPS if it doesn't exist
          echo "📂 Creating destination directory on VPS..."
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /var/www/manuel-antonio-explorer-api"

          # Create the temporary directory on VPS if it doesn't exist
          echo "📂 Creating temporary directory on VPS..."
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /var/www/manuel-antonio-explorer-api-temp"

          # Zip the published files
          echo "📦 Zipping published files..."
          cd ./api/WebStackBase.WebAPI/publish
          zip -r ../webstackbase-publish.zip .
          cd -

          # Copy the zip file to VPS
          echo "📤 Copying zip to VPS..."
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ./api/WebStackBase.WebAPI/webstackbase-publish.zip ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/manuel-antonio-explorer-api-temp/webstackbase-publish.zip

          # Backup, clean, and unzip on VPS 
          echo "🔄 Backing up, cleaning, and unzipping on VPS..."
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            DEPLOY_DIR="/var/www/manuel-antonio-explorer-api"
            BACKUP_DIR="/var/www/manuel-antonio-explorer-api-backup-$(date +%Y%m%d%H%M%S)"
            TEMP_DIR="/var/www/manuel-antonio-explorer-api-temp"
            TEMP_ZIP="/var/www/manuel-antonio-explorer-api-temp/webstackbase-publish.zip"

            # Backup existing deployment 
            echo "🗂️ Backing up existing deployment to $BACKUP_DIR"
            mv "$DEPLOY_DIR" "$BACKUP_DIR"

            # Clean up old deployment folder
            rm -rf "$DEPLOY_DIR"

            # Unzipping new files
            echo "📦 Unzipping new files..."
            unzip -o "$TEMP_ZIP" -d "$DEPLOY_DIR"

            # Clean up old temp folder and backup
            rm -rf "$TEMP_DIR"
            rm -rf "$BACKUP_DIR"

            echo "✅ Deployment completed at $DEPLOY_DIR"
          EOF
      
          # Check if the service file already exists
          echo "📝 Checking if systemd service already exists..."
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            export DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export JWT_LIFETIME="${{ secrets.JWT_LIFETIME }}"
            export SMTPSETTINGS_USERNAME="${{ secrets.SMTPSETTINGS_USERNAME }}"
            export SMTPSETTINGS_PASSWORD="${{ secrets.SMTPSETTINGS_PASSWORD }}"
            export SMTPSETTINGS_FROM="${{ secrets.SMTPSETTINGS_FROM }}"
            export TEMPLATESETTINGS_BASEPATH="${{ secrets.TEMPLATESETTINGS_BASEPATH }}"

            if [ ! -f /etc/systemd/system/manuel-antonio-explorer-api.service ]; then
              echo "⚙️ Creating systemd service..."
              cat <<EOT | envsubst | sudo tee /etc/systemd/system/manuel-antonio-explorer-api.service > /dev/null
            
          # Create systemd service file for the API if it doesn't exist
          echo "[Unit]
          Description=WebStackBase API
          After=network.target
  
          [Service]
          Environment=ASPNETCORE_ENVIRONMENT=Production
          Environment=ConnectionStrings__WebStackBase=\$DB_CONNECTION_STRING
          Environment=AuthenticationConfiguration__JwtSettings_Secret=\$JWT_SECRET
          Environment=AuthenticationConfiguration__JwtSettings_TokenLifetime=\$JWT_LIFETIME
          Environment=SmtpSettings__Username=\$SMTPSETTINGS_USERNAME
          Environment=SmtpSettings__Password=\$SMTPSETTINGS_PASSWORD
          Environment=SmtpSettings__From=\$SMTPSETTINGS_FROM
          Environment=TemplateSettings__BasePath=\$TEMPLATESETTINGS_BASEPATH
          ExecStart=/usr/bin/dotnet /var/www/manuel-antonio-explorer-api/WebStackBase.WebAPI.dll
          WorkingDirectory=/var/www/manuel-antonio-explorer-api
          Restart=always
          User=www-data
          Group=www-data
  
          [Install]
          WantedBy=multi-user.target"

          EOT
            sudo systemctl daemon-reload
            sudo systemctl enable manuel-antonio-explorer-api
            sudo systemctl start manuel-antonio-explorer-api
            echo "🚀 Systemd service created and started."
            else
              sudo systemctl restart manuel-antonio-explorer-api
              echo "✅ Systemd service already exists, skipping creation."
            fi
          EOF

          # Clean up the private key
          rm private_key

  deploy-next-site:
    name: 🚚 Deploy Manuel Antonio Explorer Site
    runs-on: ubuntu-latest
    needs: build-and-test
      
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3
        
      - name: 📦 Build Next.js site
        run: |
            cd site-public
            npm install
            npm run build

      - name: 🚀 Deploy Manuel Antonio Explorer to VPS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

          # Define directories of VPS
          SITE_DIR="/var/www/manuel-antonio-explorer"
          BACKUP_DIR="/var/www/manuel-antonio-explorer-backup-$(date +%Y%m%d%H%M%S)"
            
          # Create the destination directory if it doesn't exist
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p $SITE_DIR"

          # Verify and assign the proper permissions
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo chown -R www-data:www-data $SITE_DIR && sudo chmod -R 755 $SITE_DIR"

          # Move the current site directory to a backup folder
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mv $SITE_DIR $BACKUP_DIR || true"

          # Clean the directory
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -rf $SITE_DIR"
  
          # Copy the site
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key -r ./site-public ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$SITE_DIR
          
          # Delete the previous backup
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -rf $BACKUP_DIR"
        
          # Crear el archivo systemd para Next.js (si es necesario)
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            if [ ! -f /etc/systemd/system/manuel-antonio-explorer.service ]; then
              echo "[Unit]
              Description=Manuel Antonio Explorer Site
              After=network.target

              [Service]
              ExecStart=/usr/bin/npm run start
              WorkingDirectory=/var/www/manuel-antonio-explorer
              Restart=always
              User=www-data
              Group=www-data

              [Install]
              WantedBy=multi-user.target" | sudo tee /etc/systemd/system/manuel-antonio-explorer.service
              
              sudo systemctl daemon-reload
              sudo systemctl enable manuel-antonio-explorer
              sudo systemctl start manuel-antonio-explorer
            else
              sudo systemctl restart manuel-antonio-explorer
            fi
          EOF
        env:
          NEXT_PUBLIC_API_WEB_STACK_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_WEB_STACK_BASE_URL }}
      
      - name: Clean up
        run: rm private_key
        
  deploy-docker-compose:
    name: 🚚 Copy Docker Compose to VPS
    runs-on: ubuntu-latest
    needs: deploy-next-site
    
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3
    
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Create directory if not exists
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'mkdir -p /opt/sqlserver'
        
      - name: Ensure proper permissions for /opt/sqlserver
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} /opt/sqlserver && sudo chmod -R 755 /opt/sqlserver'
    
      - name: Copy docker-compose.sqlserver.yml to VPS
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "infra/docker-compose.sqlserver.yml" "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/opt/sqlserver/docker-compose.sqlserver.yml"
        
      - name: Verify the file on the VPS
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'ls /opt/sqlserver/docker-compose.sqlserver.yml'